spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: pro_risk_control
  datasource:
    url: jdbc:mysql://localhost:3306/pro_risk_control?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tyep: com.alibaba.druid.pool.DruidDataSource
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
  redis:
    host: 127.0.0.1
    port: 6379
server:  port: 8090

rsatime: 60000
tokentime: 60000
rateLimitNumber: 10
  